server:
  error:
    include-message: always

######## APP
app:
  version: ${version}
  name: TuC-Revision
  description: Documentaçãoo do Software de auxílio de testes de concordância TuC-Revision
  jwt:
    secret: 3bfdb43bce2657fceab0c227db17e610c972fe662369f0c601cbe0391b5c6f5a
    expiration: 7200000

######## SPRINGDOC
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

######## SPRING
spring:
  application:
    name: TuC-Revision

  ######## SWAGGER
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  ######## JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        format_sql: true
        open-in-view: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.xml

  ######## DATA SOURCE
  datasource:
    url:  jdbc:postgresql://localhost:5432/tuc-rev
    username: postgres
    password: postgres

  ######## THYMELEAF
  thymeleaf: # false é o padrão utilizado em ambientes de desenvolvimento.
    cache: false
